name: SkyMor
favicon: null
layout_spectrum: 0.8441717836540192
typography_spectrum: 0.5636870393063873
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#080a07'
    - '#d6e9ea'
    - '#32442b'
    - '#86bfce'
    - '#b66c5b'
  brandStrength: 0.5
  lightness: 0.5934212764259428
  saturation: 0.5341608417220414
  rhythmicContrast: 0.6732437070459127
purpose: []
